name: Cron - Ping Server

on:
  push:
    branches:
      - master
  schedule:
    - cron: '* * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping every 1 min
        run: |
          curl https://chat-0kc1.onrender.com/ping
