name: Cron - Ping Server

on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping every 46 seconds
        run: |
          curl https://chat-0kc1.onrender.com/ping
          sleep 46
          curl https://chat-0kc1.onrender.com/ping
